name: Test Suite
on:
  push:
    branches:
      - master
      - 'refs/pull/*'
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
#        php: [ 7.2, 7.3, 7.4, 8.0, 8.1 ]
        php: [ 7.2 ]
    name: "PHP ${{ matrix.php }} Unit Test"
    steps:
      - uses: actions/checkout@v2
      - uses: codecov/codecov-action@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: '5.0'
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: '6'
#      - uses: fabasoad/setup-cassandra-action@v1.0.0
#        with:
#          host: '127.0.0.1'
#          port: 9160
#          keyspace: oauth2_test
#          scripts_path: './scripts'
      - name: Install composer dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: composer install
      - name: Run script
        run: vendor/bin/phpunit -v
      - name: Cleanup
        run: php test/cleanup.php
